# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373

# development:
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: STRIPE_PUBLISHABLE_KEY
#   stripe_publishable_key: STRIPE_PUBLISHABLE_KEY


AWS_ACCESS_KEY_ID: AKIAITCZ5ZXEN57HB7FQ
AWS_SECRET_ACCESS_KEY: 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
# S3_BUCKET: lltv-demo
# AWS_REGION: us-east-1


STRIPE_API_KEY: sk_test_Urh1y6rqZ9fBNfp5MCzuvQXp
STRIPE_PUBLISHABLE_KEY: pk_test_ebQHY4aaHwDftEFXTHABkUFu
