development:
 host: localhost
 adapter: postgresql
 database: app_development
 pool: 5
  # username: user_name
  # password:

# test:
#   adapter: postgresql
#   host: 192.168.3.3
#   database: lltv_test
#   username: vagrant
#   password: vagrant
#   timeout: 5000
