# development:
#   adapter: postgresql
#   host: localhost
#   database: app_development
#   pool: 5


development:
  adapter: postgresql
  host: 192.168.3.3
  database: lltv
  username: vagrant
  password: vagrant
  timeout: 5000

test:
  adapter: postgresql
  host: 192.168.3.3
  database: lltv_test
  username: vagrant
  password: vagrant
  timeout: 5000
