development:
 host: localhost
 adapter: postgresql
 database: app_development
 pool: 5
  # username: user_name
  # password:

production:
 host: localhost
 adapter: postgresql
 database: lltv
 # pool: 5
  # username: user_name
  # password:

 # development:
 #   adapter: postgresql
 #   host: 192.168.3.3
 #   database: lltv
 #   username: vagrant
 #   password: vagrant
 #   timeout: 5000

# test:
#   adapter: postgresql
#   host: 192.168.3.3
#   database: lltv
#   username: vagrant
#   password: vagrant
#   timeout: 5000
#
