source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'thin'

gem 'dotenv-rails'
gem 'paperclip', '~> 4.3'

gem 'sprockets', '2.12.3'
gem 'jquery-rails'
gem 'angular_rails_csrf'
gem 'angular-rails-templates'

gem 'devise'
gem 'omniauth-linkedin-oauth2'
gem 'omniauth-facebook'
# gem 'pundit'  Model Level Policies, don't think necessary now

gem 'paperclip', '~> 4.3'

gem 'ancestry'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

