source 'https://rubygems.org'

# Russel added
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
#ruby '2.2.3'
gem 'rails', '4.2.5'
gem 'sass-rails', '~> 5.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'thin'
gem 'pg'
gem 'dotenv-rails'

gem 'sprockets', '2.12.3'

# gem 'sprockets'
# gem 'sprockets-es6'
# gem "browserify-rails"
# gem 'sprockets-es6', require: 'sprockets/es6'

gem 'jquery-rails', '~> 4.1', '>= 4.1.1'
gem 'angular_rails_csrf'
gem 'angular-rails-templates'
gem 'jquery-datatables-rails', '~> 3.3.0'
gem 'jquery-easing-rails'

gem 'devise', '3.5.6'
gem 'devise_token_auth' # , git: 'https://github.com/lynndylanhurley/devise_token_auth.git'
gem 'omniauth-linkedin-oauth2'
gem 'omniauth-facebook'
# gem 'pundit'  Model Level Policies, don't think necessary now

gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'
gem 'mini_magick'
gem 'carrierwave'
gem 'carrierwave-aws'

# Figaro to hide secret keys
gem 'figaro', '~> 1.1'
#cors
gem 'rack-cors', :require => 'rack/cors'


# gem 'aws-sdk-v1'
# gem 'aws-sdk', '~> 2'

gem 'elastic_transcoder'
# gem "active_model_serializers", "0.9.3"
gem 'active_model_serializers'

gem 'ancestry'
gem 'numbers_and_words'

gem 'puma'

gem 'bootstrap-form-helpers-rails', :git => 'https://github.com/johnu/bootstrap-form-helpers-rails.git'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  gem 'coffee-rails-source-maps'
  gem 'sass-rails-source-maps'
end

group :development do
  # gem 'hirb'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'meta_request'
  gem 'pry-awesome_print'
  gem 'pry-rails'
  gem 'quiet_assets'
  # gem 'rubocop', require: false
  gem "rails-erd"

  gem 'web-console', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'seed_dump'

  gem 'capistrano'
  gem 'capistrano3-puma'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano-rvm'
  gem 'capistrano-rbenv'
  gem 'capistrano-chruby'
  gem 'capistrano-bower'
end
