source 'https://rubygems.org'

# Russel added
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'thin'
gem 'pg'
gem 'dotenv-rails'

gem 'sprockets', '2.12.3'
gem 'jquery-rails'
gem 'angular_rails_csrf'
gem 'angular-rails-templates'
gem 'jquery-datatables-rails', '~> 3.3.0'

gem 'devise'
gem 'devise_token_auth'
gem 'omniauth-linkedin-oauth2'
gem 'omniauth-facebook'
# gem 'pundit'  Model Level Policies, don't think necessary now

gem 'paperclip'
gem 'aws-sdk-v1'
gem 'elastic_transcoder'
gem 'active_model_serializers'

gem 'ancestry'
gem 'numbers_and_words'

gem 'puma'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  gem 'hirb'
  gem "rails-erd"

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'seed_dump'

  gem 'capistrano'
  gem 'capistrano3-puma'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano-rvm'
  gem 'capistrano-rbenv'
  gem 'capistrano-chruby'
  gem 'capistrano-bower'
end
