source "https://rubygems.org"

ruby "2.0.0"

gem 'chef', github: "opscode/chef", branch: "11.6-stable"
gem 'knife-solo'
gem 'knife-ec2', github: "opscode/knife-ec2"
gem 'vagrant', github: "mitchellh/vagrant", tag: "v1.4.3"
gem 'vagrant-vbguest'
gem 'vagrant-omnibus'
gem 'vagrant-cachier'
gem 'archive-tar-minitar'
gem 'librarian-chef'
